import Head from 'next/head'
import Header from '../components/Header'
import Items from '../components/Items'
import styles from '../styles/page.module.css'
import axios from 'axios';

export default function Home({data, metadata}) {
  console.log(data.metadata)
  return (
    <div>
      <Head>
        <title>Tann Trim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Items data={data} 
         metadata={metadata}
         />
       </main>
    </div>
  )
}

export async function getServerSideProps(){
  const response=await axios.get('https://api.tjori.com/api/v7filters/na/women-all-products/?f_page=1&format=json',
  {
    responseType: 'json'
  }
  );
  const data=response.data;
  // .data;
  // const metadata=response.metadata;
    return {
      props:{
        data: data.data.products,
        metadata: data.metadata.subcategory_name
        
      }

    }
}